### ISSUE TITLE
Small test: Bug with For Each enumeration on x64 Custom Classes

### ISSUE THREAD

**Issue by SanbiVN** [cristianbuse/VBA-KeyedCollection#1]
Hi @cristianbuse 

I read your article about an error when iterating over Collection library enums in VBA 64bit.
[bug-with-for-each-enumeration-on-x64-custom-classes](https://stackoverflow.com/questions/63848617/bug-with-for-each-enumeration-on-x64-custom-classes)

I tried placing the LongPtr declarations below the ```For Each``` loop, Excel crashed when running the ```Main``` procedure.

Can you test it?

I modified like this:
```VBA
Sub ShowBug(c As CustomCollection)
    '
    Dim v As Variant
    '
    For Each v In c
    Next v
    Dim ptr0 As LongPtr
    Dim ptr1 As LongPtr
    Dim ptr2 As LongPtr
    Dim ptr3 As LongPtr
    Dim ptr4 As LongPtr
    Dim ptr5 As LongPtr
    Dim ptr6 As LongPtr
    Dim ptr7 As LongPtr
    Dim ptr8 As LongPtr
    Dim ptr9 As LongPtr
    Debug.Assert ptr0 = 0
End Sub
```

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

This sentence in the mentioned question:

> Needless to say, removing the local ptr variables inside the ShowBug method would most certainly cause the crash of the Application.

and then this one in the answer:

> If the variables would not be there, then the crash is obvious as more critical parts of memory are being overwritten 

are basically saying that if you remove the variables (or, in your case move them below), then a crash will occur. 

So, I am not surprised you got a crash.

**Comment by SanbiVN** [comment]
@cristianbuse 

I have a question?

The way to overcome this error is to call the function as follows:

```VBA
Public Function ItemsEnum() As VBA.Collection
        Set ItemsEnum = m_collItems
End Function
```

Why is the EnumHelper class necessary as you suggest?

```VBA
Public Function ItemsEnum() As EnumHelper
    With New EnumHelper
        Set .EnumVariant = m_collItems.[_NewEnum]
        Set ItemsEnum = .Self
    End With
End Function
```

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

If you return the internal collection as you did, then you break encapsulation. Now anyone can change the items in the custom collection class with something as simple as:
```VBA
With x.ItemsEnum
    .Add 15
    .Remove 1
   ....
End With
```

**Comment by SanbiVN** [comment]
Hi @cristianbuse 

My coding skills are still poor, I need to learn more. Can you share with me some coding guidelines to avoid common mistakes? Or a documentation page leading to that. Thank you very much for that much needed help.

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

I haven't read much on VBA itself but I can recommend you some really good programming books:
 - Code Complete 2 by Steve McConnell (a must read)
 - Clean Code by Robert C. Martin
 - The Practice of Programming by Brian W. Kernighan & Rob Pike

I own these (and others) and I can safely say there is a lot of knowledge inside. Happy reading!

**Comment by SanbiVN** [comment]
@cristianbuse 
Thanks you, I will search to learn more knowledge.

I see VB programmers ```wqweto```, ```The Trick (vbforums)```, ... writing code using ```thunk``` in VBA code, do you know it?
Their projects: [ModernSubclassingThunk](https://github.com/wqweto/ModernSubclassingThunk), [VbTrickTimer](https://github.com/thetrik/VbTrickTimer)

I want to learn their way of taking full advantage of API functions like ```SetTimer```, ```SetWindowLong```, ```SetWinHookEvent```, ```SetWindowSubclass```, ``` SetWindowsHookEx```.

Currently I only know one way to get around it, which is to create a new Excel process that runs in a separate thread and controls the main thread. But it's not easy.

**Comment by cristianbuse** [comment]
Hiu @SanbiVN ,

> I see VB programmers wqweto, The Trick (vbforums), ... writing code using thunk in VBA code, do you know it?
> Their projects: [ModernSubclassingThunk](https://github.com/wqweto/ModernSubclassingThunk), [VbTrickTimer](https://github.com/thetrik/VbTrickTimer)

Yes, I've seen their work. They use assembly to make those things work. You need to learn assembly in order to create such thunks.

> I want to learn their way of taking full advantage of API functions like SetTimer, SetWindowLong, SetWinHookEvent, SetWindowSubclass,  SetWindowsHookEx.

The official MSDN documentation is quite good and whenever I need to use an API, I simply go to MSDN.

You would probably benefit by reading about COM (Component Object Model)  because VB* is basically COM compliant under the hood.

**Comment by SanbiVN** [comment]
Hi @cristianbuse

I'm starting to learn Assembly programming. I understand the API functions above. I just want to take advantage of ```thunk``` like them, to solve the problem of app crashes and sudden closings.
